#!/usr/bin/python

import os
import sys
import signal
import time
import subprocess

def shellGetOutput(str) :
    process = subprocess.Popen(str,shell=True,stdout=subprocess.PIPE,
                               stderr=subprocess.PIPE)
    output, err = process.communicate()

    return output

print "\n********Running varying hyperedges experiments********\n"


threads = shellGetOutput("nproc --all")

print "Number of threads on machine = " + threads


dataDir = "../../inputs/"

applications = ["HyperBFS","HyperBC","HyperCC","HyperPageRank","HyperKCore-Efficient","HyperKCore"]
mis = ["HyperMIS"]
wapplications = ["HyperSSSP"]

testfiles = [("rand-10M-10M-10-ligrah","0"),("rand-10M-20M-10-ligrah","0"),("rand-10M-30M-10-ligrah","0"),("rand-10M-40M-10-ligrah","0"),("rand-10M-50M-10-ligrah","0"),("rand-10M-60M-10-ligrah","0"),("rand-10M-70M-10-ligrah","0"),("rand-10M-80M-10-ligrah","0"),("rand-10M-90M-10-ligrah","0"),("rand-10M-100M-10-ligrah","0")]

wtestfiles = [("rand-10M-10M-10-wgh-ligrah","0"),("rand-10M-20M-10-wgh-ligrah","0"),("rand-10M-30M-10-wgh-ligrah","0"),("rand-10M-40M-10-wgh-ligrah","0"),("rand-10M-50M-10-wgh-ligrah","0"),("rand-10M-60M-10-wgh-ligrah","0"),("rand-10M-70M-10-wgh-ligrah","0"),("rand-10M-80M-10-wgh-ligrah","0"),("rand-10M-90M-10-wgh-ligrah","0"),("rand-10M-100M-10-wgh-ligrah","0")]

processors = [int(threads)]

os.system("export CILK=1; make clean; make -j")

for app in applications:
  for testfile in testfiles :
    for p in processors :
      if p <= 4:
          ss = "export CILK_NWORKERS="+`p`+"; ./"+app+' -s -rounds 1 -maxiters 1 -r '+testfile[1]+' '+dataDir+testfile[0]
      else:
          ss = "export CILK_NWORKERS="+`p`+"; numactl -i all ./" + app + ' -s -rounds 3 -maxiters 1 -r '+testfile[1]+ ' ' + dataDir + testfile[0]
          print app+" "+`p` + " thread(s) on " + testfile[0] 
          print shellGetOutput(ss)
          sys.stdout.flush()

for app in mis:
  for testfile in testfiles :
    for p in processors :
      if p <= 4:
          ss = "export CILK_NWORKERS="+`p`+"; ./"+app+' -s -rounds 0 -maxiters 1 -r '+testfile[1]+' '+dataDir+testfile[0]
      else:
          ss = "export CILK_NWORKERS="+`p`+"; numactl -i all ./" + app + ' -s -rounds 0 -maxiters 1 -r '+testfile[1]+ ' ' + dataDir + testfile[0]
          print app+" "+`p` + " threads(s) on " + testfile[0] 
          print shellGetOutput(ss)
          sys.stdout.flush()

for app in wapplications:
  for testfile in wtestfiles :
    for p in processors :
      if p <= 4:
          ss = "export CILK_NWORKERS="+`p`+"; ./"+app+' -s -rounds 1 -r '+testfile[1]+' '+dataDir+testfile[0]
      else:
          ss = "export CILK_NWORKERS="+`p`+"; numactl -i all ./" + app + ' -s -rounds 3 -r '+testfile[1]+' ' + dataDir + testfile[0]
          print app+" "+`p` + " thread(s) on " + testfile[0]
          print shellGetOutput(ss)
          sys.stdout.flush()
