#!/usr/bin/python

import os
import sys
import signal
import time
import subprocess

def shellGetOutput(str) :
  process = subprocess.Popen(str,shell=True,stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE)
  output, err = process.communicate()
  
  return output

print "Running varying threshold experiments..."


threads = shellGetOutput("nproc --all")

print "Number of threads on machine = " + threads


dataDir = "../../inputs/"

applications = ["HyperBFS-Threshold","HyperBC-Threshold","HyperCC-Threshold"]
wapplications = ["HyperSSSP-Threshold"]

testfiles = [("com-orkut-ligrah","0"),("livejournal-ligrah","0")]

wtestfiles = [("com-orkut-wgh-ligrah","0"),("livejournal-wgh-ligrah","0")]

processors = [int(threads)]

print processors

os.system("export CILK=1; make clean; make -j")

for app in applications:
  for testfile in testfiles :
    if testfile[0] in edgeawarefiles:
      edgeaware = "-EdgeAware"
    else:
      edgeaware = ""
    for t in thresholds:
      for p in processors :
        if p <= 4:
          ss = "export CILK_NWORKERS="+`p`+"; ./"+app+edgeaware+' -s -rounds 1 -maxiters 1 -r '+testfile[1]+' -t ' +`t`+' '+dataDir+testfile[0]
        else:
          ss = "export CILK_NWORKERS="+`p`+"; numactl -i all ./" + app+edgeaware+ + ' -s -maxiters 1 -r '+testfile[1]+ ' -t ' + `t` + ' ' + dataDir + testfile[0]
        print app+edgeaware+" "+`p` + " " + `t` + " " + testfile[0] 
        print shellGetOutput(ss)
        sys.stdout.flush()

for app in wapplications:
  for testfile in wtestfiles :
    if testfile[0] in edgeawarefiles:
      edgeaware = "-EdgeAware"
    else:
      edgeaware = ""
    for t in thresholds:
      for p in processors :
        if p <= 4:
          ss = "export CILK_NWORKERS="+`p`+"; ./"+app+edgeaware+' -s -rounds 1 -maxiters 1 -r '+testfile[1]+' -t ' +`t`+' '+dataDir+testfile[0]
        else:
          ss = "export CILK_NWORKERS="+`p`+"; numactl -i all ./" + app+edgeaware + ' -s -maxiters 1 -r '+testfile[1]+ ' -t ' + `t` + ' ' + dataDir + testfile[0]
        print app+edgeaware+" "+`p` + " " + `t` + " " + testfile[0] 
        print shellGetOutput(ss)
        sys.stdout.flush()
