#!/usr/bin/python

import os
import sys
import signal
import time
import subprocess

def shellGetOutput(str) :
  process = subprocess.Popen(str,shell=True,stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE)
  output, err = process.communicate()
  
  return output

print "\n********Running varying threshold experiments********\n"


threads = shellGetOutput("nproc --all")

print "Number of threads on machine = " + threads


dataDir = "../../inputs/"

applications = ["HyperBFS-Threshold","HyperBC-Threshold","HyperCC-Threshold"]
wapplications = ["HyperSSSP-Threshold"]

testfiles = [("com-orkut-hygra","0"),("livejournal-hygra","0")]

wtestfiles = [("com-orkut-wgh-hygra","0"),("livejournal-wgh-hygra","0")]

edgeawarefiles=["livejournal-hygra","livejournal-wgh-hygra"]

processors = [int(threads)]

thresholds = range(1,10,1)+range(10,101,10)+[1000,10000,100000,1000000,10000000,100000000]                   

os.system("export CILK=1; make clean; make threshold -j")

for app in applications:
  for testfile in testfiles :
    if testfile[0] in edgeawarefiles:
      edgeaware = "-EdgeAware"
    else:
      edgeaware = ""
    for t in thresholds:
      for p in processors :
        if p <= 4:
          ss = "export CILK_NWORKERS="+`p`+"; ./"+app+edgeaware+' -s -rounds 1 -maxiters 1 -r '+testfile[1]+' -t ' +`t`+' '+dataDir+testfile[0]
        else:
          ss = "export CILK_NWORKERS="+`p`+"; numactl -i all ./" + app+edgeaware + ' -s -maxiters 1 -r '+testfile[1]+ ' -t ' + `t` + ' ' + dataDir + testfile[0]
        print app+edgeaware+" "+`p` + " thread(s) on " + testfile[0] + " with threshold = sum-of-degrees/" + `t` 
        print shellGetOutput(ss)
        sys.stdout.flush()

for app in wapplications:
  for testfile in wtestfiles :
    if testfile[0] in edgeawarefiles:
      edgeaware = "-EdgeAware"
    else:
      edgeaware = ""
    for t in thresholds:
      for p in processors :
        if p <= 4:
          ss = "export CILK_NWORKERS="+`p`+"; ./"+app+edgeaware+' -s -rounds 1 -maxiters 1 -r '+testfile[1]+' -t ' +`t`+' '+dataDir+testfile[0]
        else:
          ss = "export CILK_NWORKERS="+`p`+"; numactl -i all ./" + app+edgeaware + ' -s -maxiters 1 -r '+testfile[1]+ ' -t ' + `t` + ' ' + dataDir + testfile[0]
        print app+edgeaware+" "+`p` + " thread(s) on " + testfile[0] + " with threshold = sum-of-degrees/" + `t` 
        print shellGetOutput(ss)
        sys.stdout.flush()
